### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by Philo** [FredrikL/Cake.FluentMigrator#1]
HI @FredrikL,
I was wondering what the status of this project is, I see that it hasnt been updated in a while and it isnt listed on the cakebuild.net website.  I was looking to implement this exact Cake addin myself but initially wanted to see whether you were still actively looking to maintain your version before going off and doing my own thing?

If you are not interested in maintaining this going forward I would be happy to take over.

**Comment by FredrikL** [comment]
Hi @Philo 

I'm currently not working on any dotnet projects so if you want to take over this project feel free to.

**Comment by jjschlesinger** [comment]
Hi @Philo,

Are you currently working on this? I am also working on integrating FM with cake. Let me know if you are still interested in this. Just trying not to double up on the same thing.

-Josh

**Comment by Philo** [comment]
Hi,

While it was my plan to look at updating this add in I haven't had time to be it yet, so happy to put it in your hands 😀
